default: &default
 adapter: mysql2
 encoding: utf8mb4
 collation: utf8mb4_bin
 reconnect: false
 pool: 50
 username: root
 password: root
 port: 3306
 host: mysql
 socket: /var/run/mysqld/mysqlx.sock

development:
 <<: *default
 database: ChatAPI_development

production:
 <<: *default
 database: ChatAPI